language: python
python:
  - 3.8
env:
  - BUILD=docker
before_script:
  - sudo service postgresql stop
script:
  - docker-compose -f docker-compose.travis.yml build lutrisfrontend lutrisweb
  - docker-compose -f docker-compose.travis.yml run -e DJANGO_SETTINGS_MODULE='lutrisweb.settings.travis' -w '/app' lutrisweb bash -c "touch templates/docs/installers.html && make db && make test"

# Build Notifications
# https://docs.travis-ci.com/user/notifications/
notifications:
  # Turn off email notifications entirely.
  email: false
